apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: busybox-1
  name: busybox-1
spec:
  selector:
    matchLabels:
      workload: busybox-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: busybox-1
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        args:
          - while true; 
            file=/mnt/test/data_`date +%s`;
            hashfile=/mnt/test/hashfile;
            do dd if=/dev/urandom of=$file bs=$(($RANDOM)) count=$(($RANDOM%3+1));
            md5sum $file >>$hashfile;
            sync;
            sleep 15;
            if [ $(($RANDOM%2)) == 1 ]; then md5sum -c $hashfile; fi;
            done
        image: quay.io/vcppds7878/busybox:latest
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/test
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: busybox-pvc-1
          readOnly: false
